### ISSUE TITLE
PyScratch errors at line 147 and 167 of main.py

### ISSUE THREAD

**Issue by rwbaer** [ElsevierSoftwareX/PyScratch#2]
I have tried to run PyScratch, but I end up with an error that loops on the console. I am running on Windows 11 using Anaconda python and VS Studio Code.  

Alternatively, is there a  more recent version of PyScratch that runs better with more recent python and more recent dependencies?

It appears to be related to pyqt loop, but I caan't be sure.  Do you have any advice on how to preceed?  Thanks in advance for your help.

Here is my dependency list:
```
py37) D:\PythonProjects\pyscratch_public>python -V
Python 3.7.15

(py37) D:\PythonProjects\pyscratch_public>conda list
# packages in environment at C:\Users\rbaer\anaconda3\envs\py37:
#
# Name                    Version                   Build  Channel
ca-certificates           2022.10.11           haa95532_0
certifi                   2022.9.24        py37haa95532_0
cycler                    0.11.0                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py37haa95532_0
powershell_shortcut       0.0.1                         3
pyparsing                 3.0.9                    pypi_0    pypi
pyqt5                     5.15.7                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.0                  pypi_0    pypi
pyside2                   5.15.2.1                 pypi_0    pypi
python                    3.7.15               h6244533_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.6                   pypi_0    pypi
setuptools                65.5.0           py37haa95532_0
shiboken2                 5.15.2.1                 pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.40.0               h2bbff1b_0
style                     1.1.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
update                    0.0.1                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py37haa95532_2
```

Here is the looping error that I get when I run **_python main.py_** from the VS Code terminal:
```
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
Traceback (most recent call last):
  File "main.py", line 382, in progress
    self.runMain()
  File "main.py", line 361, in runMain
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
Traceback (most recent call last):
  File "main.py", line 382, in progress
    self.runMain()
  File "main.py", line 361, in runMain
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
Traceback (most recent call last):
  File "main.py", line 382, in progress
    self.runMain()
  File "main.py", line 361, in runMain
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
Traceback (most recent call last):
  File "main.py", line 382, in progress
    self.runMain()
  File "main.py", line 361, in runMain
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
Traceback (most recent call last):
  File "main.py", line 382, in progress
    self.runMain()
  File "main.py", line 361, in runMain
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
Traceback (most recent call last):
  File "main.py", line 382, in progress
    self.runMain()
  File "main.py", line 361, in runMain
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
Traceback (most recent call last):
  File "main.py", line 382, in progress
    self.runMain()
  File "main.py", line 361, in runMain
    self.main = MainDialog()
  File "main.py", line 147, in __init__
    self.setPlots()
  File "main.py", line 167, in setPlots
    self.plot_area.addWidget(self.canvas)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
```

**Comment by rwbaer** [comment]
I don't know exactly what is wrong here, but authors maintain the version at https://bitbucket.org/vladgaal/pyscratch_public.git 

I'm closing this and made an issue #3 stating as much.
